import type {
  AnalysisResult,
  AttributeCandidate,
  DataObjectDraft,
  EventDraft,
  InteractionName,
  PageTypeDraft,
} from '@/types/analysis'

// Pure, deterministic transform: AnalysisResult → sitemap.js source.
// The Sitemap Code tab in Result is always derived from the current state via this function.

export function codeFromAnalysis(analysis: AnalysisResult): string {
  const lines: string[] = []
  lines.push('// Generated by Sitemap Consultant Workbench')
  lines.push('// Site: ' + analysis.site.url)
  lines.push('')

  // Emit helper functions referenced by field expressions
  const helpers = collectRequiredHelpers(analysis)
  if (helpers.has('readJsonLd')) {
    lines.push('function readJsonLd(key) {')
    lines.push('  var scripts = document.querySelectorAll(\'script[type="application/ld+json"]\');')
    lines.push('  for (var i = 0; i < scripts.length; i++) {')
    lines.push('    try {')
    lines.push('      var data = JSON.parse(scripts[i].textContent);')
    lines.push('      if (data[key] !== undefined) return data[key];')
    lines.push('      if (data["@graph"]) {')
    lines.push('        for (var j = 0; j < data["@graph"].length; j++) {')
    lines.push('          if (data["@graph"][j][key] !== undefined) return data["@graph"][j][key];')
    lines.push('        }')
    lines.push('      }')
    lines.push('    } catch (e) { /* skip malformed JSON-LD */ }')
    lines.push('  }')
    lines.push('  return undefined;')
    lines.push('}')
    lines.push('')
  }

  const hasConsent = analysis.attributes.some(
    (a) => a.category === 'Consent' && a.review?.state !== 'rejected',
  )

  lines.push('SalesforceInteractions.init({')
  lines.push('  cookieDomain: "' + safeDomain(analysis.site.url) + '",')
  if (hasConsent) {
    lines.push('  consents: [{')
    lines.push('    purpose: SalesforceInteractions.mcis.ConsentPurpose.Personalization,')
    lines.push('    provider: "Example Consent Manager", // TODO: replace with your consent manager')
    lines.push('    status: SalesforceInteractions.ConsentStatus.OptIn,')
    lines.push('  }],')
  }
  lines.push('}).then(() => {')

  // Resolve locale for global config
  const localeAttr = analysis.attributes.find(
    (a) => a.name === 'language' && a.category === 'Locale' && a.review?.state !== 'rejected',
  )

  lines.push('  const sitemapConfig = {')
  lines.push('    global: {')
  if (localeAttr) {
    lines.push('      locale: ' + guessLocaleValue(analysis) + ',')
  }
  renderOnActionEvent(lines, analysis)
  renderGlobalContentZones(lines)
  renderGlobalListeners(lines, analysis)
  lines.push('    },')

  // pageTypeDefault
  lines.push('    pageTypeDefault: {')
  lines.push('      name: "default",')
  lines.push('      interaction: {')
  lines.push('        name: "Default Page",')
  lines.push('      },')
  lines.push('    },')

  lines.push('    pageTypes: [')
  const activePts = analysis.pageTypes
    .filter((pt) => pt.review?.state !== 'rejected')
    .sort((a, b) => {
      const aExact = a.isMatchHint.includes('===') ? 0 : 1
      const bExact = b.isMatchHint.includes('===') ? 0 : 1
      return aExact - bExact
    })
  for (const pt of activePts) {
    renderPageType(lines, pt, analysis)
  }
  lines.push('    ],')
  lines.push('  };')
  lines.push('  SalesforceInteractions.initSitemap(sitemapConfig);')
  lines.push('})')
  lines.push('')
  return lines.join('\n')
}

// ——— global.onActionEvent ———

function renderOnActionEvent(lines: string[], analysis: AnalysisResult): void {
  const activeAttrs = analysis.attributes.filter(
    (a) => a.review?.state !== 'rejected' && a.status !== 'excluded',
  )
  const identityAttrs = activeAttrs.filter((a) => a.category === 'Identity')
  const userAttrs = activeAttrs.filter(
    (a) => a.category !== 'Identity' && a.category !== 'Consent',
  )

  const hasIdentity = identityAttrs.length > 0
  const hasUserAttrs = userAttrs.length > 0

  if (!hasIdentity && !hasUserAttrs) {
    lines.push('      onActionEvent: (actionEvent) => actionEvent,')
    return
  }

  lines.push('      onActionEvent: (actionEvent) => {')
  lines.push('        actionEvent.user = actionEvent.user || {};')

  if (hasIdentity) {
    lines.push('')
    lines.push('        // Identity capture — resolve the user across sessions')
    lines.push('        actionEvent.user.identities = actionEvent.user.identities || {};')
    lines.push('        const email = SalesforceInteractions.mcis.getValueFromNestedObject(')
    lines.push('          "window._etmc.user_info.email"')
    lines.push('        );')
    lines.push('        if (email) {')
    lines.push('          actionEvent.user.identities.emailAddress = email;')
    lines.push('        }')
  }

  if (hasUserAttrs) {
    lines.push('')
    lines.push('        // User attributes')
    lines.push('        actionEvent.user.attributes = actionEvent.user.attributes || {};')
    for (const attr of userAttrs) {
      const expr = attributeExpression(attr)
      if (expr) {
        lines.push('        actionEvent.user.attributes.' + attr.name + ' = { value: ' + expr + ' };')
      }
    }
  }

  lines.push('')
  lines.push('        return actionEvent;')
  lines.push('      },')
}

function attributeExpression(attr: AttributeCandidate): string | null {
  switch (attr.name) {
    case 'language':
      return 'document.documentElement.lang'
    case 'market':
      if (attr.proposedSource.includes('URL'))
        return 'window.location.pathname.split("/").filter(Boolean)[0]'
      return 'document.documentElement.lang?.split("-")[1]'
    case 'loginStatus':
      return 'document.querySelector(".logout, [href*=logout], [href*=signout]") ? "logged_in" : "anonymous"'
    case 'customerType':
      return null
    case 'locale':
      return 'document.documentElement.lang'
    default:
      return null
  }
}

// ——— global.contentZones ———

function renderGlobalContentZones(lines: string[]): void {
  lines.push('      contentZones: [')
  lines.push('        { name: "global_infobar_top_of_page", selector: "header" },')
  lines.push('        { name: "global_infobar_bottom_of_page", selector: "footer" },')
  lines.push('      ],')
}

// ——— global.listeners (email signup) ———

function renderGlobalListeners(lines: string[], analysis: AnalysisResult): void {
  const hasIdentity = analysis.attributes.some(
    (a) => a.category === 'Identity' && a.review?.state !== 'rejected',
  )
  if (!hasIdentity) return

  lines.push('      listeners: [')
  lines.push('        SalesforceInteractions.listener("submit", ".email-signup, .newsletter-form", () => {')
  lines.push('          const emailInput = document.querySelector(\'input[type="email"], input[name*="email"]\');')
  lines.push('          const email = emailInput ? emailInput.value : null;')
  lines.push('          if (email) {')
  lines.push('            SalesforceInteractions.sendEvent({')
  lines.push('              interaction: { name: "Email Sign Up" },')
  lines.push('              user: {')
  lines.push('                identities: { emailAddress: email },')
  lines.push('              },')
  lines.push('            });')
  lines.push('          }')
  lines.push('        }),')
  lines.push('      ],')
}

function collectRequiredHelpers(analysis: AnalysisResult): Set<string> {
  const helpers = new Set<string>()
  for (const obj of analysis.dataObjects) {
    for (const f of obj.fields) {
      if (f.source === 'jsonLd') helpers.add('readJsonLd')
    }
  }
  return helpers
}

function renderPageType(
  lines: string[],
  pt: PageTypeDraft,
  analysis: AnalysisResult,
): void {
  lines.push('      {')
  lines.push('        name: ' + jsString(pt.name) + ',')
  lines.push('        isMatch: () => ' + compileIsMatch(pt.isMatchHint) + ', // ' + pt.isMatchHint)
  const object = pt.objectRefs[0]
    ? analysis.dataObjects.find((d) => d.id === pt.objectRefs[0])
    : undefined
  if (pt.interactionName && object) {
    lines.push('        interaction: {')
    lines.push('          name: SalesforceInteractions.' + interactionNamespace(pt.interactionName) + '.' + pt.interactionName + ',')
    renderCatalogObject(lines, object, 10)
    lines.push('        },')
  } else if (pt.interactionName) {
    lines.push('        interaction: {')
    lines.push('          name: SalesforceInteractions.' + interactionNamespace(pt.interactionName) + '.' + pt.interactionName + ',')
    lines.push('        },')
  }
  const events = analysis.events.filter(
    (e) => pt.eventRefs.includes(e.id) && e.review?.state !== 'rejected',
  )
  if (events.length > 0) {
    lines.push('        listeners: [')
    for (const ev of events) renderListener(lines, ev, analysis)
    lines.push('        ],')
  }
  lines.push('      },')
}

function renderCatalogObject(
  lines: string[],
  object: DataObjectDraft,
  indent: number,
): void {
  const pad = ' '.repeat(indent)
  lines.push(pad + 'catalogObject: {')
  lines.push(pad + '  type: ' + jsString(object.type) + ',')
  for (const field of object.fields) {
    lines.push(pad + '  ' + field.name + ': ' + fieldExpression(field) + ',')
  }
  lines.push(pad + '},')
}

function renderListener(lines: string[], ev: EventDraft, analysis: AnalysisResult): void {
  const isLoginEvent = ev.customName === 'Logged In' || ev.customName === 'Login'
  lines.push('          SalesforceInteractions.listener(')
  if (ev.kind === 'interaction' && ev.interactionName) {
    lines.push('            "click",')
    lines.push('            ' + jsString(selectorFromHint(ev.triggerHint)) + ',')
    lines.push('            () => {')
    lines.push('              SalesforceInteractions.sendEvent({')
    lines.push('                interaction: {')
    lines.push('                  name: SalesforceInteractions.' + interactionNamespace(ev.interactionName) + '.' + ev.interactionName + ',')
    const object = ev.objectRef
      ? analysis.dataObjects.find((d) => d.id === ev.objectRef)
      : undefined
    if (object) renderCatalogObject(lines, object, 18)
    lines.push('                },')
    lines.push('              });')
    lines.push('            }')
  } else if (ev.kind === 'customEvent' && ev.customName) {
    const eventType = isLoginEvent ? '"submit"' : '"click"'
    lines.push('            ' + eventType + ',')
    lines.push('            ' + jsString(selectorFromHint(ev.triggerHint)) + ',')
    lines.push('            () => {')
    if (isLoginEvent) {
      lines.push('              const emailInput = document.querySelector(\'input[type="email"], input[name*="email"]\');')
      lines.push('              const email = emailInput ? emailInput.value : null;')
      lines.push('              SalesforceInteractions.sendEvent({')
      lines.push('                interaction: { name: ' + jsString(ev.customName) + ' },')
      lines.push('                user: {')
      lines.push('                  identities: {')
      lines.push('                    emailAddress: email || undefined,')
      lines.push('                  },')
      lines.push('                },')
      lines.push('              });')
    } else {
      lines.push('              SalesforceInteractions.sendEvent({')
      lines.push('                interaction: { name: ' + jsString(ev.customName) + ' },')
      lines.push('              });')
    }
    lines.push('            }')
  }
  lines.push('          ),')
}

function interactionNamespace(name: InteractionName): string {
  if (name === 'AddToCart' || name === 'UpdateLineItem' || name === 'RemoveFromCart' || name === 'ViewCart') {
    return 'CartInteractionName'
  }
  if (name === 'Purchase') return 'OrderInteractionName'
  return 'CatalogObjectInteractionName'
}

function fieldExpression(field: { name: string; source: string; selectorHint?: string }): string {
  switch (field.source) {
    case 'jsonLd':
      return 'readJsonLd(' + jsString(field.name) + ')'
    case 'dataLayer':
      return '(function() { var dl = window.dataLayer || []; for (var i = dl.length - 1; i >= 0; i--) { if (dl[i] && dl[i][' + jsString(field.name) + '] !== undefined) return dl[i][' + jsString(field.name) + ']; } return undefined; })()'
    case 'dom':
      return 'document.querySelector(' + jsString(field.selectorHint || '') + ')?.textContent?.trim()'
    case 'url':
      return 'window.location.pathname.split("/").filter(Boolean).pop() /* TODO: map URL segment to catalog ID */'
    default:
      return 'undefined /* TODO: configure ' + field.source + ' source */'
  }
}

function compileIsMatch(hint: string): string {
  // pathname === "/exact/path"
  const eq = hint.match(/pathname\s*===?\s*["']([^"']+)["']/i)
  if (eq) return 'window.location.pathname === ' + jsString(eq[1])
  // pathname starts with /prefix/
  const starts = hint.match(/starts with\s+["']?([^\s"']+)/i)
  if (starts) return 'window.location.pathname.startsWith(' + jsString(starts[1]) + ')'
  // pathname matches /template/:id
  const matches = hint.match(/pathname matches\s+(.+)/i)
  if (matches) {
    const re = matches[1]
      .replace(/:[a-zA-Z]+/g, '[^/]+')
      .replace(/\//g, '\\/')
    return 'new RegExp("^' + re + '$").test(window.location.pathname)'
  }
  return 'false /* TODO: configure isMatch for — ' + hint + ' */'
}

function selectorFromHint(hint: string): string {
  const match = hint.match(/(button[.#\w-]+|[.#][\w-]+)/)
  if (match) return match[1]
  const lower = hint.toLowerCase()
  if (lower.includes('add-to-cart') || lower.includes('add to cart'))
    return '.add-to-cart, [data-action="add-to-cart"]'
  if (lower.includes('login') || lower.includes('sign-in') || lower.includes('sign in'))
    return 'form[name="login-form"] button[type="submit"], .login-form button[type="submit"]'
  if (lower.includes('checkout'))
    return '.checkout-button, [data-action="checkout"]'
  if (lower.includes('submit'))
    return 'button[type="submit"]'
  return hint
}

function safeDomain(url: string): string {
  try {
    return new URL(url).hostname
  } catch {
    return ''
  }
}

function jsString(value: string): string {
  return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
}

function guessLocaleValue(analysis: AnalysisResult): string {
  const langSignal = analysis.site.sampledPages
    .flatMap((p) => p.signals)
    .find((s) => s.startsWith('html:lang='))
  if (langSignal) {
    const lang = langSignal.replace('html:lang=', '').replace('-', '_')
    return jsString(lang)
  }
  return '"en_US" // TODO: set locale'
}
