import type {
  AnalysisResult,
  DataObjectDraft,
  EventDraft,
  InteractionName,
  PageTypeDraft,
} from '@/types/analysis'

// Pure, deterministic transform: AnalysisResult → sitemap.js source.
// The Sitemap Code tab in Result is always derived from the current state via this function.

export function codeFromAnalysis(analysis: AnalysisResult): string {
  const lines: string[] = []
  lines.push('// Generated by Sitemap Consultant Workbench')
  lines.push('// Site: ' + analysis.site.url)
  lines.push('')
  lines.push('SalesforceInteractions.init({')
  lines.push('  cookieDomain: "' + safeDomain(analysis.site.url) + '",')
  lines.push('}).then(() => {')
  lines.push('  SalesforceInteractions.initSitemap({')
  lines.push('    global: {')
  lines.push('      onActionEvent: (actionEvent) => actionEvent,')
  lines.push('    },')
  lines.push('    pageTypes: [')
  for (const pt of analysis.pageTypes) {
    renderPageType(lines, pt, analysis)
  }
  lines.push('    ],')
  lines.push('  })')
  lines.push('})')
  lines.push('')
  return lines.join('\n')
}

function renderPageType(
  lines: string[],
  pt: PageTypeDraft,
  analysis: AnalysisResult,
): void {
  lines.push('      {')
  lines.push('        name: ' + jsString(pt.name) + ',')
  lines.push('        isMatch: () => ' + compileIsMatch(pt.isMatchHint) + ', // ' + pt.isMatchHint)
  const object = pt.objectRefs[0]
    ? analysis.dataObjects.find((d) => d.id === pt.objectRefs[0])
    : undefined
  if (pt.interactionName && object) {
    lines.push('        interaction: {')
    lines.push('          name: SalesforceInteractions.' + interactionNamespace(pt.interactionName) + '.' + pt.interactionName + ',')
    renderCatalogObject(lines, object, 10)
    lines.push('        },')
  } else if (pt.interactionName) {
    lines.push('        interaction: {')
    lines.push('          name: SalesforceInteractions.' + interactionNamespace(pt.interactionName) + '.' + pt.interactionName + ',')
    lines.push('        },')
  }
  const events = analysis.events.filter((e) => pt.eventRefs.includes(e.id))
  if (events.length > 0) {
    lines.push('        listeners: [')
    for (const ev of events) renderListener(lines, ev, analysis)
    lines.push('        ],')
  }
  lines.push('      },')
}

function renderCatalogObject(
  lines: string[],
  object: DataObjectDraft,
  indent: number,
): void {
  const pad = ' '.repeat(indent)
  lines.push(pad + 'catalogObject: {')
  lines.push(pad + '  type: ' + jsString(object.type) + ',')
  for (const field of object.fields) {
    lines.push(pad + '  ' + field.name + ': ' + fieldExpression(field) + ',')
  }
  lines.push(pad + '},')
}

function renderListener(lines: string[], ev: EventDraft, analysis: AnalysisResult): void {
  lines.push('          {')
  if (ev.kind === 'interaction' && ev.interactionName) {
    lines.push('            selector: ' + jsString(selectorFromHint(ev.triggerHint)) + ',')
    lines.push('            handler: (event) => SalesforceInteractions.sendEvent({')
    lines.push('              interaction: {')
    lines.push('                name: SalesforceInteractions.' + interactionNamespace(ev.interactionName) + '.' + ev.interactionName + ',')
    const object = ev.objectRef
      ? analysis.dataObjects.find((d) => d.id === ev.objectRef)
      : undefined
    if (object) renderCatalogObject(lines, object, 16)
    lines.push('              },')
    lines.push('            }),')
  } else if (ev.kind === 'customEvent' && ev.customName) {
    lines.push('            selector: ' + jsString(selectorFromHint(ev.triggerHint)) + ',')
    lines.push('            handler: (event) => SalesforceInteractions.sendEvent({')
    lines.push('              interaction: { name: ' + jsString(ev.customName) + ' },')
    lines.push('            }),')
  }
  lines.push('          },')
}

function interactionNamespace(name: InteractionName): string {
  if (name === 'AddToCart' || name === 'UpdateLineItem' || name === 'RemoveFromCart' || name === 'ViewCart') {
    return 'CartInteractionName'
  }
  if (name === 'Purchase') return 'OrderInteractionName'
  return 'CatalogObjectInteractionName'
}

function fieldExpression(field: { name: string; source: string; selectorHint?: string }): string {
  switch (field.source) {
    case 'jsonLd':
      return 'readJsonLd(' + jsString(field.name) + ')'
    case 'dataLayer':
      return 'window.dataLayer && window.dataLayer.' + field.name
    case 'dom':
      return 'document.querySelector(' + jsString(field.selectorHint || '') + ')?.textContent?.trim()'
    case 'url':
      return 'parseUrl(' + jsString(field.name) + ')'
    default:
      return 'undefined /* ' + field.source + ' */'
  }
}

function compileIsMatch(hint: string): string {
  const lower = hint.toLowerCase()
  const eq = lower.match(/pathname\s*===?\s*["']([^"']+)["']/)
  if (eq) return 'window.location.pathname === ' + jsString(eq[1])
  const starts = lower.match(/starts with\s*["']?([^"'\s]+)/)
  if (starts) return 'window.location.pathname.startsWith(' + jsString(starts[1]) + ')'
  return 'false /* unresolved: ' + hint + ' */'
}

function selectorFromHint(hint: string): string {
  const match = hint.match(/(button[.#\w-]+|[.#][\w-]+)/)
  return match ? match[1] : hint
}

function safeDomain(url: string): string {
  try {
    return new URL(url).hostname
  } catch {
    return ''
  }
}

function jsString(value: string): string {
  return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
}
