import type {
  AnalysisResult,
  DataObjectDraft,
  EventDraft,
  InteractionName,
  PageTypeDraft,
} from '@/types/analysis'

// Pure, deterministic transform: AnalysisResult → sitemap.js source.
// The Sitemap Code tab in Result is always derived from the current state via this function.

export function codeFromAnalysis(analysis: AnalysisResult): string {
  const lines: string[] = []
  lines.push('// Generated by Sitemap Consultant Workbench')
  lines.push('// Site: ' + analysis.site.url)
  lines.push('')

  // Emit helper functions referenced by field expressions
  const helpers = collectRequiredHelpers(analysis)
  if (helpers.has('readJsonLd')) {
    lines.push('function readJsonLd(key) {')
    lines.push('  var scripts = document.querySelectorAll(\'script[type="application/ld+json"]\');')
    lines.push('  for (var i = 0; i < scripts.length; i++) {')
    lines.push('    try {')
    lines.push('      var data = JSON.parse(scripts[i].textContent);')
    lines.push('      if (data[key] !== undefined) return data[key];')
    lines.push('      if (data["@graph"]) {')
    lines.push('        for (var j = 0; j < data["@graph"].length; j++) {')
    lines.push('          if (data["@graph"][j][key] !== undefined) return data["@graph"][j][key];')
    lines.push('        }')
    lines.push('      }')
    lines.push('    } catch (e) { /* skip malformed JSON-LD */ }')
    lines.push('  }')
    lines.push('  return undefined;')
    lines.push('}')
    lines.push('')
  }

  lines.push('SalesforceInteractions.init({')
  lines.push('  cookieDomain: "' + safeDomain(analysis.site.url) + '",')
  lines.push('}).then(() => {')
  lines.push('  SalesforceInteractions.initSitemap({')
  lines.push('    global: {')
  lines.push('      onActionEvent: (actionEvent) => actionEvent,')
  lines.push('    },')
  lines.push('    pageTypes: [')
  const activePts = analysis.pageTypes
    .filter((pt) => pt.review?.state !== 'rejected')
    .sort((a, b) => {
      const aExact = a.isMatchHint.includes('===') ? 0 : 1
      const bExact = b.isMatchHint.includes('===') ? 0 : 1
      return aExact - bExact
    })
  for (const pt of activePts) {
    renderPageType(lines, pt, analysis)
  }
  lines.push('    ],')
  lines.push('  })')
  lines.push('})')
  lines.push('')
  return lines.join('\n')
}

function collectRequiredHelpers(analysis: AnalysisResult): Set<string> {
  const helpers = new Set<string>()
  for (const obj of analysis.dataObjects) {
    for (const f of obj.fields) {
      if (f.source === 'jsonLd') helpers.add('readJsonLd')
    }
  }
  return helpers
}

function renderPageType(
  lines: string[],
  pt: PageTypeDraft,
  analysis: AnalysisResult,
): void {
  lines.push('      {')
  lines.push('        name: ' + jsString(pt.name) + ',')
  lines.push('        isMatch: () => ' + compileIsMatch(pt.isMatchHint) + ', // ' + pt.isMatchHint)
  const object = pt.objectRefs[0]
    ? analysis.dataObjects.find((d) => d.id === pt.objectRefs[0])
    : undefined
  if (pt.interactionName && object) {
    lines.push('        interaction: {')
    lines.push('          name: SalesforceInteractions.' + interactionNamespace(pt.interactionName) + '.' + pt.interactionName + ',')
    renderCatalogObject(lines, object, 10)
    lines.push('        },')
  } else if (pt.interactionName) {
    lines.push('        interaction: {')
    lines.push('          name: SalesforceInteractions.' + interactionNamespace(pt.interactionName) + '.' + pt.interactionName + ',')
    lines.push('        },')
  }
  const events = analysis.events.filter(
    (e) => pt.eventRefs.includes(e.id) && e.review?.state !== 'rejected',
  )
  if (events.length > 0) {
    lines.push('        listeners: [')
    for (const ev of events) renderListener(lines, ev, analysis)
    lines.push('        ],')
  }
  lines.push('      },')
}

function renderCatalogObject(
  lines: string[],
  object: DataObjectDraft,
  indent: number,
): void {
  const pad = ' '.repeat(indent)
  lines.push(pad + 'catalogObject: {')
  lines.push(pad + '  type: ' + jsString(object.type) + ',')
  for (const field of object.fields) {
    lines.push(pad + '  ' + field.name + ': ' + fieldExpression(field) + ',')
  }
  lines.push(pad + '},')
}

function renderListener(lines: string[], ev: EventDraft, analysis: AnalysisResult): void {
  lines.push('          {')
  if (ev.kind === 'interaction' && ev.interactionName) {
    lines.push('            selector: ' + jsString(selectorFromHint(ev.triggerHint)) + ',')
    lines.push('            handler: (event) => SalesforceInteractions.sendEvent({')
    lines.push('              interaction: {')
    lines.push('                name: SalesforceInteractions.' + interactionNamespace(ev.interactionName) + '.' + ev.interactionName + ',')
    const object = ev.objectRef
      ? analysis.dataObjects.find((d) => d.id === ev.objectRef)
      : undefined
    if (object) renderCatalogObject(lines, object, 16)
    lines.push('              },')
    lines.push('            }),')
  } else if (ev.kind === 'customEvent' && ev.customName) {
    lines.push('            selector: ' + jsString(selectorFromHint(ev.triggerHint)) + ',')
    lines.push('            handler: (event) => SalesforceInteractions.sendEvent({')
    lines.push('              interaction: { name: ' + jsString(ev.customName) + ' },')
    lines.push('            }),')
  }
  lines.push('          },')
}

function interactionNamespace(name: InteractionName): string {
  if (name === 'AddToCart' || name === 'UpdateLineItem' || name === 'RemoveFromCart' || name === 'ViewCart') {
    return 'CartInteractionName'
  }
  if (name === 'Purchase') return 'OrderInteractionName'
  return 'CatalogObjectInteractionName'
}

function fieldExpression(field: { name: string; source: string; selectorHint?: string }): string {
  switch (field.source) {
    case 'jsonLd':
      return 'readJsonLd(' + jsString(field.name) + ')'
    case 'dataLayer':
      return '(function() { var dl = window.dataLayer || []; for (var i = dl.length - 1; i >= 0; i--) { if (dl[i] && dl[i][' + jsString(field.name) + '] !== undefined) return dl[i][' + jsString(field.name) + ']; } return undefined; })()'
    case 'dom':
      return 'document.querySelector(' + jsString(field.selectorHint || '') + ')?.textContent?.trim()'
    case 'url':
      return 'window.location.pathname.split("/").filter(Boolean).pop() /* TODO: map URL segment to catalog ID */'
    default:
      return 'undefined /* TODO: configure ' + field.source + ' source */'
  }
}

function compileIsMatch(hint: string): string {
  const lower = hint.toLowerCase()
  // pathname === "/exact/path"
  const eq = hint.match(/pathname\s*===?\s*["']([^"']+)["']/i)
  if (eq) return 'window.location.pathname === ' + jsString(eq[1])
  // pathname starts with /prefix/
  const starts = hint.match(/starts with\s+["']?([^\s"']+)/i)
  if (starts) return 'window.location.pathname.startsWith(' + jsString(starts[1]) + ')'
  // pathname matches /template/:id
  const matches = hint.match(/pathname matches\s+(.+)/i)
  if (matches) {
    const re = matches[1]
      .replace(/:[a-zA-Z]+/g, '[^/]+')
      .replace(/\//g, '\\/')
    return 'new RegExp("^' + re + '$").test(window.location.pathname)'
  }
  return 'false /* TODO: configure isMatch for — ' + hint + ' */'
}

function selectorFromHint(hint: string): string {
  const match = hint.match(/(button[.#\w-]+|[.#][\w-]+)/)
  return match ? match[1] : hint
}

function safeDomain(url: string): string {
  try {
    return new URL(url).hostname
  } catch {
    return ''
  }
}

function jsString(value: string): string {
  return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
}
