// Generates a professional Markdown document summarizing the tracking design.
// Intended audience: the client (non-technical stakeholders) or the
// consultant's project record. Excluded/rejected items are listed separately
// so the client can see they were considered.

import type { AnalysisResult } from '@/types/analysis'

export function designDocFromAnalysis(analysis: AnalysisResult): string {
  const lines: string[] = []
  const domain = safeDomain(analysis.site.url)
  const now = new Date().toISOString().split('T')[0]

  // ——— Header ———
  lines.push('# Salesforce Personalization — Tracking Design')
  lines.push('')
  lines.push(`**Site:** ${analysis.site.url}  `)
  lines.push(`**Date:** ${now}  `)
  if (analysis.site.platform) {
    lines.push(`**Platform:** ${analysis.site.platform}  `)
  }
  lines.push(`**Generated by:** Sitemap Consultant Workbench`)
  lines.push('')
  lines.push('---')
  lines.push('')

  // ——— Executive Summary ———
  const activePts = analysis.pageTypes.filter((pt) => pt.review?.state !== 'rejected')
  const activeEvents = analysis.events.filter((e) => e.review?.state !== 'rejected')
  const activeAttrs = analysis.attributes.filter(
    (a) => a.review?.state !== 'rejected' && a.status !== 'excluded',
  )
  const confirmedCount = activePts.filter((pt) => pt.review?.state === 'confirmed').length
  const pendingCount = activePts.filter(
    (pt) => !pt.review || pt.review.state === 'pending',
  ).length

  lines.push('## Executive Summary')
  lines.push('')
  lines.push(
    `- **${activePts.length} Page Types** identified (${confirmedCount} confirmed, ${pendingCount} pending review)`,
  )
  lines.push(`- **${activeEvents.length} Tracked Events** (commerce interactions + custom)`)
  lines.push(
    `- **${activeAttrs.length} User Attributes** for personalization targeting`,
  )
  lines.push(
    `- **${analysis.dataObjects.length} Catalog Objects** (Product, Category, Cart, etc.)`,
  )
  if (analysis.assumptions.length > 0) {
    lines.push(
      `- **${analysis.assumptions.length} Assumptions** — review before implementation`,
    )
  }
  lines.push('')

  // ——— Page Types ———
  lines.push('## Page Types')
  lines.push('')
  if (activePts.length === 0) {
    lines.push('No active page types.')
  } else {
    lines.push(
      '| # | Name | Match Rule | Interaction | Confidence | Status |',
    )
    lines.push(
      '|---|------|-----------|-------------|------------|--------|',
    )
    activePts.forEach((pt, i) => {
      const status = pt.review?.state === 'confirmed' ? 'Confirmed' : 'Pending'
      const interaction = pt.interactionName ?? '—'
      lines.push(
        `| ${i + 1} | ${pt.name} | \`${pt.isMatchHint}\` | ${interaction} | ${pt.confidence} | ${status} |`,
      )
    })
  }
  lines.push('')

  // ——— Catalog Objects ———
  if (analysis.dataObjects.length > 0) {
    lines.push('## Catalog Objects')
    lines.push('')
    for (const obj of analysis.dataObjects) {
      lines.push(`### ${obj.label} (${obj.type})`)
      lines.push('')
      lines.push('| Field | Source | Selector | Required |')
      lines.push('|-------|--------|----------|----------|')
      for (const f of obj.fields) {
        lines.push(
          `| ${f.name} | ${f.source} | ${f.selectorHint ? '`' + f.selectorHint + '`' : '—'} | ${f.required ? 'Yes' : 'No'} |`,
        )
      }
      lines.push('')
    }
  }

  // ——— Events ———
  if (activeEvents.length > 0) {
    lines.push('## Tracked Events')
    lines.push('')
    lines.push('| Event | Type | Trigger | Page Types | Status |')
    lines.push('|-------|------|---------|------------|--------|')
    for (const e of activeEvents) {
      const name =
        e.kind === 'interaction'
          ? e.interactionName ?? 'interaction'
          : e.customName ?? 'custom'
      const ptNames = e.pageTypeRefs
        .map((ref) => analysis.pageTypes.find((pt) => pt.id === ref)?.name)
        .filter(Boolean)
        .join(', ')
      const status =
        e.review?.state === 'confirmed' ? 'Confirmed' : 'Pending'
      lines.push(`| ${name} | ${e.kind} | ${e.triggerHint} | ${ptNames || '—'} | ${status} |`)
    }
    lines.push('')
  }

  // ——— Identity & Data Capture Strategy ———
  const identityAttrs = activeAttrs.filter((a) => a.category === 'Identity')
  const consentAttrs = activeAttrs.filter((a) => a.category === 'Consent')
  const hasLoginEvent = activeEvents.some(
    (e) => e.customName === 'Logged In' || e.customName === 'Login',
  )

  lines.push('## Identity & Data Capture Strategy')
  lines.push('')
  if (identityAttrs.length > 0 || hasLoginEvent || consentAttrs.length > 0) {
    lines.push('### Consent')
    lines.push('')
    if (consentAttrs.length > 0) {
      lines.push(
        '- Consent banner detected — `SalesforceInteractions.init()` should gate on consent status',
      )
      lines.push(
        '- Configure the `consents` array in `init()` with your consent manager provider name',
      )
    } else {
      lines.push('- No consent banner detected — verify with the client before deploying without consent gating')
    }
    lines.push('')

    lines.push('### Identity Resolution')
    lines.push('')
    lines.push(
      '- **Global `onActionEvent`**: Captures `user.identities.emailAddress` from data layer / SFMC tag on every page',
    )
    if (hasLoginEvent) {
      lines.push(
        '- **Login listener**: Captures email identity on form submission and sends a "Logged In" event',
      )
    }
    lines.push(
      '- **Email signup listener**: Captures email identity from newsletter / signup forms in global scope',
    )
    lines.push(
      '- Identity attributes accumulate across pages in a single visit for improved resolution',
    )
    lines.push('')
  } else {
    lines.push('No identity signals detected. User tracking will be anonymous-only until identity sources are configured.')
    lines.push('')
  }

  // ——— User Attributes ———
  lines.push('## User Attributes')
  lines.push('')
  if (activeAttrs.length === 0) {
    lines.push(
      'No user attributes detected. Personalization targeting will rely on page type alone.',
    )
  } else {
    lines.push('| Attribute | Category | Source | Confidence | Action Required |')
    lines.push('|-----------|----------|--------|------------|-----------------|')
    for (const a of activeAttrs) {
      lines.push(
        `| ${a.name} | ${a.category} | ${a.proposedSource} | ${a.confidence} | ${a.consultantAction} |`,
      )
    }
  }
  lines.push('')

  // ——— Requirement Mappings ———
  if (analysis.requirementMappings.length > 0) {
    lines.push('## Requirement Traceability')
    lines.push('')
    lines.push('| Requirement | Mapped To | Status |')
    lines.push('|-------------|-----------|--------|')
    for (const rm of analysis.requirementMappings) {
      const target = rm.targets
        .map((t) => {
          if (t.pageTypeRef) {
            return analysis.pageTypes.find((pt) => pt.id === t.pageTypeRef)?.name
          }
          if (t.attributeRef) {
            return analysis.attributes.find((a) => a.id === t.attributeRef)?.name
          }
          return null
        })
        .filter(Boolean)
        .join(', ')
      lines.push(`| ${rm.text} | ${target || '(unmapped)'} | ${rm.status} |`)
    }
    lines.push('')
  }

  // ——— Exclusions ———
  const exclusions = analysis.attributes.filter(
    (a) => a.status === 'excluded' || a.review?.state === 'rejected',
  )
  const rejectedPts = analysis.pageTypes.filter(
    (pt) => pt.review?.state === 'rejected',
  )
  if (exclusions.length > 0 || rejectedPts.length > 0) {
    lines.push('## Exclusions & Rejected Items')
    lines.push('')
    if (rejectedPts.length > 0) {
      lines.push('**Rejected Page Types:**')
      for (const pt of rejectedPts) {
        lines.push(
          `- ~~${pt.name}~~ — ${pt.review?.note || 'No reason given'}`,
        )
      }
      lines.push('')
    }
    if (exclusions.length > 0) {
      lines.push('**Excluded Attributes:**')
      for (const a of exclusions) {
        lines.push(
          `- ~~${a.name}~~ (${a.category}) — ${a.review?.note || a.consultantAction}`,
        )
      }
      lines.push('')
    }
  }

  // ——— Assumptions ———
  if (analysis.assumptions.length > 0) {
    lines.push('## Assumptions & Limitations')
    lines.push('')
    for (const a of analysis.assumptions) {
      lines.push(`- ${a}`)
    }
    lines.push('')
  }

  // ——— Next Steps ———
  lines.push('## Next Steps')
  lines.push('')
  const steps: string[] = []
  if (pendingCount > 0) {
    steps.push(
      `Review and confirm the ${pendingCount} pending page type(s) in the Workbench`,
    )
  }
  const manualSelectors = analysis.events.filter(
    (e) =>
      e.triggerHint.includes('button') ||
      e.triggerHint.includes('click') ||
      e.triggerHint.includes('selector'),
  )
  if (manualSelectors.length > 0) {
    steps.push(
      `Verify ${manualSelectors.length} event selector(s) on the live site (inspect DOM for exact selectors)`,
    )
  }
  const lowConfAttrs = activeAttrs.filter((a) => a.confidence === 'low')
  if (lowConfAttrs.length > 0) {
    steps.push(
      `Confirm runtime sources for ${lowConfAttrs.length} low-confidence attribute(s)`,
    )
  }
  steps.push('Deploy sitemap.js to the site via SFMC tag or manual injection')
  steps.push('Validate tracking in the Salesforce Interactions Event Stream')

  steps.forEach((s, i) => {
    lines.push(`${i + 1}. ${s}`)
  })
  lines.push('')

  // ——— Footer ———
  lines.push('---')
  lines.push('')
  lines.push(
    `*Generated by Salesforce Personalization Workbench by DentsuDigital — ${now}*`,
  )
  lines.push('')

  return lines.join('\n')
}

function safeDomain(url: string): string {
  try {
    return new URL(url).hostname
  } catch {
    return ''
  }
}
